alias l='eza --icons --git --group-directories-first --long'
alias la='eza --icons --git --group-directories-first --long --all --group'
alias ll='eza --icons --git --group-directories-first --long --group --header'
alias lla='eza --icons --git --group-directories-first --long --all --group --header'
alias lt='eza --icons --git --group-directories-first --tree --level=2'
alias llt='eza --icons --git --group-directories-first --tree --level=4'
alias lr='eza --icons --git --group-directories-first --long --recurse'