set -g default-terminal "tmux-256color"
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set-window-option -g mode-keys vi

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Start window index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Clear pane output
bind -n C-x send-keys -R \; clear-history
bind l send-keys -R \; clear-history

# Hyprland instance signature
set-hook -g client-attached 'run-shell "tmux set-environment -g HYPRLAND_INSTANCE_SIGNATURE $(ls /tmp/hypr | head -n1)"'

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-processes 'make "log*" k9s btop lazydocker opencode nvim'

# Fork for fixing this issue: https://github.com/catppuccin/tmux/pull/577
set -g @plugin 'Thumzu/catppuccin-tmux'
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag, 󰁌 ,}"
set -g @catppuccin_window_text " #W"


set -g status-position top
set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right "#{E:@catppuccin_status_application}"

run '~/.local/share/tmux/plugins/tpm/tpm'

set -g status-bg default
set -g status-style bg=default
